# Generated by Django 4.2.7 on 2026-03-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('gym', 'Gym'), ('yoga', 'Yoga'), ('swimming', 'Swimming'), ('walking', 'Walking'), ('hiit', 'HIIT'), ('stretching', 'Stretching'), ('other', 'Other')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=6, null=True)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='medium', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
